version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-pos
    container_name: api-pos
    restart: unless-stopped
    ports:
      - "8005:80"  # Expose the application on port 8005
      - "443:443"  # Expose the application on port 443 for HTTPS
    volumes:
      - ./api:/var/www
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./config/ssl:/etc/nginx/ssl
      - ./config/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf 
      - ./logs/nginx:/var/log/nginx
    networks:
      - my_custom_network
    environment:
      APP_KEY: base64:fcXCweRmLveeyW39ckoKRRKyaW3N9oPxMdonnzPSLyU=
      DB_CONNECTION: mysql
      DB_HOST: mysql  # Use the service name for the database host
      DB_PORT: 3306
      DB_DATABASE: db_pos
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_custom_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my_custom_network

networks:
  my_custom_network:
    external: true

volumes:
  mysql_data:
