import {Dimensions, StyleSheet} from 'react-native';

export default StyleSheet.create({
  body: {
    position: 'relative',
    width: '100%',
    height: '100%',
    backgroundColor: '#f5f5f5',
  },
  navbar: {
    width: '100%',
    height: '5%',
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    top: 35,
    padding: 20,
    zIndex: 9,
  },
  item: {
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    paddingTop: 10,
    alignItems: 'center',
    width: Dimensions.get('window').width / 2 - 33,
    // minWidth: 160,
    // maxWidth: '47%',
    // width: 'auto',
    minHeight: 70,
    borderColor: '#aaa',
    borderWidth: 1,
    borderRadius: 10,
    margin: 7,
    flexDirection: 'column',
    backgroundColor: '#fafafa',
  },
  itemImg: {
    width: '100%',
    minHeight: 120,
    height: 'auto',
    borderRadius: 10,
  },
  itemTextName: {
    color: '#333',
    width: '100%',
    textAlign: 'center',
    fontWeight: '600',
    marginTop: 5,
    fontSize: 14,
  },
  itemViewDetail: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  itemTextPrice: {
    color: '#333',
    width: '100%',
    fontWeight: '600',
    fontSize: 12,
  },
  itemImgDiscount: {
    width: 27,
    height: 27,
    position: 'absolute',
    top: -5,
    right: 0,
  },
  itemViewPcs: {
    marginLeft: 7,
    width: '17%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnCart: {
    width: '100%',
    marginTop: 10,
    height: 30,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    display: 'flex',
    flexDirection: 'row',
  },
  wrapDetailProduct: {
    zIndex: 10,
    height: '100%',
    maxHeight: '100%',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  backDrop: {
    width: '100%',
    height: '100%',
    backgroundColor: '#000000b7',
    zIndex: 9,
    position: 'absolute',
    top: 0,
  },
  containerBottomSheet: {
    backgroundColor: 'white',
    padding: 20,
    position: 'relative',
  },
  imgDetailProduct: {
    width: '100%',
    minHeight: 250,
    height: 'auto',
    borderRadius: 10,
    marginBottom: 10,
  },
  textDetailProduct: {
    color: '#444',
    fontSize: 20,
    fontWeight: '500',
    marginBottom: 10,
  },
  imgDiscountDetailProduct: {
    width: 70,
    height: 70,
    top: 20,
    right: 5,
  },
  wrapBtnDetailProduct: {
    display: 'flex',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  btnDetailProduct: {
    height: 40,
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  itemCart: {
    display: 'flex',
    justifyContent: 'space-between',
    position: 'relative',
    padding: 10,
    alignItems: 'center',
    width: '100%',
    minHeight: 70,
    borderColor: '#aaa',
    borderWidth: 1,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    flexDirection: 'row',
    backgroundColor: '#fafafa',
  },
  itemCartImg: {
    width: '10%',
    height: 30,
    borderRadius: 10,
  },
  itemCartTextName: {
    color: '#333',
    marginLeft: 8,
    width: '25%',
    fontSize: 14,
  },
  itemCartViewPcs: {
    marginLeft: 7,
    width: '35%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemCartImgDiscount: {
    width: 27,
    height: 27,
    position: 'absolute',
    top: -5,
    right: 0,
  },
  wrapItemCart: {
    width: '100%',
    height: '7%',
    paddingHorizontal: 18,
    marginBottom: 30,
    backgroundColor: '#fff',
  },
  shadowItemCart: {
    shadowColor: '#171717',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.4,
    shadowRadius: 3,
  },
  btnItemCart: {
    width: '100%',
    minHeight: 55,
    height: 'auto',
    paddingHorizontal: 20,
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#608B55',
    borderRadius: 20,
    marginBottom: 25,
  },
  textItemCart: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 18,
  },
  wrapPriceCart: {
    width: '75%',
    height: '100%',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  textPriceCart: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 16,
  },
  textItemKeranjang: {
    paddingHorizontal: 20,
    fontSize: 20,
    color: '#000',
    fontWeight: '600',
    marginBottom: 20,
    marginTop: 10,
  },
  wrapFooterCart: {
    width: '100%',
    borderTopWidth: 2,
    borderColor: '#ccc',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  wrapSubFooter: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  textFooterCart: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    textAlign: 'right',
  },
  wrapSubSubFooter: {
    width: '63%',
    paddingRight: 20,
    borderRightWidth: 1,
    paddingVertical: 15,
    borderColor: '#ccc',
  },
});
