import {Dimensions, Platform, StyleSheet} from 'react-native';

export default StyleSheet.create({
  body: {
    position: 'relative',
    width: '100%',
    height: Dimensions.get('screen').height,
    backgroundColor: '#f5f5f5',
  },
  header: {
    width: '100%',
    position: 'absolute',
    top: 0,
  },
  headerImg: {
    width: '100%',
    height: 250,
  },
  headerWrapText: {
    width: '100%',
    height: 250,
    position: 'absolute',
    top: 0,
    backgroundColor: '#00000080',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    fontSize: 25,
    color: '#fff',
    fontWeight: '800',
    fontFamily: 'Arial',
  },
  headerTextMak: {
    fontSize: 50,
    color: '#fff',
    fontFamily: 'GloriaHallelujah-Regular',
  },
  headerRoundedBottom: {
    position: 'absolute',
    backgroundColor: '#f5f5f5',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    height: 20,
    bottom: 0,
  },
  wrapCard: {
    width: '100%',
    height: 400,
    marginTop: Platform.OS === 'ios' ? '45%' : '65%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    flexWrap: 'wrap',
    padding: 20,
  },
  btnCard: {
    width: '43%',
    height: '43%',
    position: 'relative',
    borderColor: '#bbb',
    backgroundColor: '#fafafa',
    borderWidth: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 25,
    margin: 10,
    borderRadius: 20,
  },
  wrapBtnCard: {
    paddingTop: 16,
    width: '100%',
    height: '100%',
  },
  imgCard: {
    width: '100%',
    height: '100%',
  },
  textCard: {
    marginTop: 8,
    color: '#555',
    fontSize: 20,
    marginBottom: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  btnHostname: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#C9EDDC',
    padding: 10,
    borderColor: '#bbb',
    borderWidth: 1,
    width: 70,
    height: 70,
    borderRadius: 100,
  },
  btnImgHostname: {
    width: '100%',
    height: '100%',
  },
  btnImgShadow: {
    position: 'absolute',
    bottom: '10%',
    right: '8%',
    shadowColor: '#04251D',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.3,
    shadowRadius: 7,
  },
});
